name: Offshore Wind Infrastructure Update

on:
  #schedule:
    # Runs at 00:00 UTC every day
  #  - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual run for testing

permissions:
  contents: write

jobs:
  update-offshore-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          channels: conda-forge, esri
          activate-environment: arcgis-api
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          # Install spatial C-libraries via Conda for stability
          conda install -c conda-forge gdal=3.10.0 geopandas fiona -y --quiet
          # Install remaining logic/API libraries via Pip
          pip install arcgis==2.4.1.* pandas numpy requests python-dotenv

      - name: Execute Python script
        shell: bash -l {0}
        run: python python/noaa_enc_processor/main.py
        env:
          PYTHONDONTWRITEBYTECODE: 1
          ARCGIS_URL: ${{ secrets.ARCGIS_URL }}
          ARCGIS_CLIENT_ID: ${{ secrets.ARCGIS_CLIENT_ID }}
          ARCGIS_CLIENT_SECRET: ${{ secrets.ARCGIS_CLIENT_SECRET }}

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit and Push ENC Updates
        run: |
          git add data-raw/ENC/
          if ! git diff --cached --quiet; then
            git commit -m "Automated update: New NOAA ENC data"
            git push origin main
          else
            echo "No changes detected in data-raw/ENC, skipping push."
          fi
        
          