name: Offshore Wind Infrastructure Update

on:
  schedule:
    # This runs at 00:00 UTC every day
    #- cron: '0 0 * * *'
  workflow_dispatch: # Allows manual run for testing

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 2. Setup Conda environment
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          channels: conda-forge, esri
          activate-environment: arcgis-api
          auto-activate-base: false

      # 3. Install dependencies
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge gdal=3.11.4 -y --quiet
          pip install arcgis==2.4.1.* pandas numpy requests geopandas fiona python-dotenv

      # 4. Run Script
      - name: Execute Python script
        shell: bash -l {0}
        run: python python/noaa_enc_processor/main.py
        env:
          ARCGIS_URL: ${{ secrets.ARCGIS_URL }}
          ARCGIS_CLIENT_ID: ${{ secrets.ARCGIS_CLIENT_ID }}
          ARCGIS_CLIENT_SECRET: ${{ secrets.ARCGIS_CLIENT_SECRET }}

      # Pushes any updated files back to GitHub
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update: $(date)" || echo "No changes to commit"
          git push
        
          